### PR TITLE
Add eslint and lint files.

### PR DESCRIPTION
**Pull request by tjgupta**
No code or functionality change, just added linting so that we can catch silly errors like unintentional global vars, etc and also use a consistent style across the JS.

You should be able to configure your editor to use the .eslintrc.js config file to show you errors as you go, and if you want to quickly fix them run `npm run lint`.

### CODE REVIEW

**Comment by Dfenestrator** [comment]
Can you outline what linting rules we're using here, and what kind of enforcement we're using? Also, if we're going to go this path would you be able to add instructions on auto-linting on save for the editors? I use Vim for most of my stuff.

Overall I would rather we kept linting as light as possible. Given that we're working on volunteer time and the project is still small, I for one don't want to spend time fixing linting issues.

If the automated tool is good though and handles this fully, and our linting rules are light enough, then I think it can make sense.

**Comment by tjgupta** [comment]
@Dfenestrator I set it to use the rules defined here:
http://standardjs.com/#the-rules

I also overrode the following rules from standardjs to match more with the style we already had across the codebase:
- indent 4 spaces rather than 2
- use semicolons
- no space before function parens
- warn when using console.log (this I added only because it's not really a good practice to do this in browser code, but we have it throughout so for now it's just warning)

There is no enforcement at this point (that would probably have to be done with some sort of build process, which I don't think we really have yet). The point was definitely not to add more to anyone's plate - in fact, I did it to try to reduce overhead by making it super quick to bring consistency to a file (`npm run lint`) and catching silly mistakes (like global vars or unused vars) before they become bugs. 

If you were interested in taking advantage of the linting assistance in vim, you could do something like this:
https://medium.com/@khanght/using-eslint-with-vim-817c08151b70#.paj5mdb06

That being said, you wouldn't necessarily have to, since, as I mentioned I'm not proposing enforcement right now, just a baseline to start with and assistance for (at least) myself as code is edited.

Here are the various eslint plugins:
http://eslint.org/docs/user-guide/integrations

**Comment by tjgupta** [comment]
This is now rebased off of the signup_page branch and should be good to go once https://github.com/helloGov/singleAction/pull/109 gets merged in.

**Comment by Dfenestrator** [comment]
My vote is for no semicolon enforcement and no function spacing

**Comment by Dfenestrator** [comment]
Did you want to rebase this? or just merge now

**Comment by tjgupta** [comment]
It's rebased again. Should be good to go.

**Pull request merged**
