### PR TITLE
Fix campaign URLs so they don't collide with root URLs.

### PR DESCRIPTION
**Pull request by tjgupta**
This is additive to #119 so merge that first.

This is to fix a few different issues:
- We weren't prefixing the campaign URLs with anything, so it was a variable right at the root. This meant any mistyped URL at the root would trigger a DB lookup for a campaign, and has the (remote) possibility of URL collisions. Also meant when you add URLs they had to be in just the right order so that the campaign URL was last, otherwise it would match before, say, "/settings" or "/join" or "/share" or whatever we decide to add in the future.
- In fixing the above issue I discovered that the campaign updating wasn't happening correctly but was instead always creating a new campaign.
- I also pulled out the campaign URL where possible so that it's derived from the Campaign model, in case we decide to change the format again.

### CODE REVIEW

**Comment by WCRest** [comment]
This looks good, but can we think of a better way of preventing campaign URLs from colliding with non-campaign URLs? I know a user will likely never type in a URL, so we're not really asking the user to modify their behavior, but I think it makes sense to make our core content accessible from root URLs. 
Further, I'm ok with a mistyped URL resulting in a DB lookup --  it makes sense that URLs are resolved by first checking from a list of system URLs (/create, /home, /login,) then upon failure checking to see if the URL exists as a campaign ID, then upon failure of that issuing a 404. 
I don't feel strongly enough about this to not merge it in, since I wouldn't block launch because our system couldn't elegantly support campaign URLs accessible as root URLs.

**Comment by tjgupta** [comment]
Yeah, I agree it does look a bit better having the campaigns on the root - it just makes things a bit trickier in the app. The biggest nuisance to me was that it makes the order of the routes matter (makes the routing more brittle), but if we think it's pretty important to have the campaigns right at the root (hellogov.org/[campaignId] vs hellogov.org/c/[campaignId]) I can switch it back. I don't know of any other way to do that without it being the way it was. Well, actually one alternative is we could prefix the ID with some pattern, like `hellogov.org/c-[campaignId]`, but personally that seems about the same as `/c/[campaignId]`.

What's your preference? I'll switch this PR to whichever pattern...should be easier to change now. :) 

We do want to solidify the URL scheme for this before launch obviously, since these are the URLs that will be shared.

**Comment by WCRest** [comment]
I agree that `c-` prefixes for campaign IDs would be a compromise.  My preference is to continue using campaign IDs as root URLs, but I think we should add comments wherever the order of this route is defined: where we define the campaign routing endpoint, and when we `require` the routing file that includes this definition.

**Comment by tjgupta** [comment]
Sounds good, I'll switch it back to that in this PR.

**Comment by tjgupta** [comment]
@WCRest this is all set now and ready to merge - back to the root campaign URLs. Note that if we decide to add public user profiles down the road we will not be able to do them at the root like hellogov.org/timgupta with this scheme. But we could probably just do hellogov.org/u/timgupta or similar instead.

**Pull request merged**
